"use client";
import {useEffect,useMemo,useState} from "react";
const money=n=>new Intl.NumberFormat("nb-NO").format(n)+" kr";
export default function Home(){
 const [view,setView]=useState("home"),[toast,setToast]=useState("");
 const [goDraft,setGoDraft]=useState(null);
 const [receipts,setReceipts]=useState([{id:1,supplier:"ESSVE Norge",date:"24.09.2026",total:1847,mva:369,status:"Klar til godkjenning"}]);
 const [invoices,setInvoices]=useState([{id:"1001",customer:"Byggmester Hansen AS",total:31250,due:"08.10.2026",status:"Sendt"}]);
 const [bank,setBank]=useState([{id:1,text:"Innbetaling faktura 1001",amount:31250,matched:true},{id:2,text:"Circle K",amount:-1240,matched:false},{id:3,text:"Montér",amount:-3890,matched:false}]);
 const totals=useMemo(()=>({sales:248500,cost:161200,result:87300,mva:18420}),[]);
 const done=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 useEffect(()=>{try{const params=new URLSearchParams(window.location.search);if(params.get("from")==="rala-go"&&params.get("handoff")==="1"){const raw=sessionStorage.getItem("rala-regnskap-handoff");if(raw){const draft=JSON.parse(raw);if(draft?.source==="rala-go"){setGoDraft(draft);setView("receipt");sessionStorage.removeItem("rala-regnskap-handoff")}}}}catch{}},[]);
 const acceptGoDraft=()=>{if(!goDraft)return;setReceipts(rs=>[{id:"GO-"+goDraft.sourceRef,supplier:goDraft.supplier||"RALA",date:new Date().toLocaleDateString("nb-NO"),total:Number(goDraft.amountIncVat||0),mva:Number(goDraft.vatAmount||0),status:"Testkladd fra RALA GO"},...rs]);setGoDraft(null);done("Testkjøpet fra RALA GO er lagt inn som kladd ✓")};
 const Back=()=> <button className="back" onClick={()=>setView("home")}>← Tilbake</button>;
 if(view==="receipt")return <main><header><Logo/><button>Testfirma ▾</button></header><section className="work"><Back/><small>KJØP</small><h1>Jeg har kjøpt noe</h1><p className="lead">Legg inn kvitteringen. RALA foreslår resten.</p>{goDraft&&<div className="goImport"><small>RALA GO · TESTOVERFØRING</small><h2>Kjøpet kom fra RALA GO ✓</h2><p><b>{goDraft.supplier||"RALA"}</b>{goDraft.project?` · ${goDraft.project}`:""}</p><p className="goImportItems">{goDraft.description||"Bestilling fra RALA GO"}</p><div><span>Eks. MVA <b>{money(Number(goDraft.amountExVat||0))}</b></span><span>MVA <b>{money(Number(goDraft.vatAmount||0))}</b></span><span>Inkl. MVA <strong>{money(Number(goDraft.amountIncVat||0))}</strong></span></div><button className="primary" onClick={acceptGoDraft}>Legg inn som testkladd</button><button className="goImportCancel" onClick={()=>setGoDraft(null)}>Ikke legg inn</button></div>}<div className="panel"><label>Leverandør<input defaultValue="ESSVE Norge"/></label><div className="twocol"><label>Beløp inkl. MVA<input defaultValue="1847"/></label><label>MVA<input defaultValue="369"/></label></div><label>Kategori<select defaultValue="Verktøy og materiell"><option>Verktøy og materiell</option><option>Bil og transport</option><option>Kontor</option><option>Annet</option></select></label><label className="upload">📷 Ta bilde / last opp kvittering<input type="file" accept="image/*,.pdf"/></label><button className="primary" onClick={()=>done("Kvittering lagret som kladd ✓")}>Godkjenn forslag</button></div><h2>Siste kvitteringer</h2>{receipts.map(r=><div className="row" key={r.id}><div><b>{r.supplier}</b><span>{r.date} · {r.status}</span></div><strong>{money(r.total)}</strong></div>)}</section>{toast&&<Toast t={toast}/>}</main>;
 if(view==="invoice")return <main><header><Logo/><button>Testfirma ▾</button></header><section className="work"><Back/><small>FAKTURA</small><h1>Jeg skal ha betalt</h1><p className="lead">Hvem skal betale, hva har du gjort og hvor mye?</p><div className="panel"><label>Kunde<input placeholder="Søk eller skriv kundenavn"/></label><label>Hva har du gjort?<textarea placeholder="F.eks. rens og montering av takrenner"/></label><div className="twocol"><label>Beløp eks. MVA<input placeholder="0"/></label><label>MVA<select><option>25 %</option><option>15 %</option><option>12 %</option><option>0 %</option></select></label></div><button className="primary" onClick={()=>done("Fakturakladd opprettet ✓")}>Lag fakturakladd</button></div><h2>Fakturaer</h2>{invoices.map(x=><div className="row" key={x.id}><div><b>#{x.id} · {x.customer}</b><span>Forfall {x.due} · {x.status}</span></div><strong>{money(x.total)}</strong></div>)}</section>{toast&&<Toast t={toast}/>}</main>;
 if(view==="bank")return <main><header><Logo/><button>Testfirma ▾</button></header><section className="work"><Back/><small>BANK</small><h1>Hva må matches?</h1><p className="lead">RALA viser bare det du trenger å ta stilling til.</p>{bank.map(x=><div className="row bank" key={x.id}><div><b>{x.text}</b><span>{x.matched?"✓ Matchet":"Trenger handling"}</span></div><strong className={x.amount>0?"plus":""}>{x.amount>0?"+":""}{money(x.amount)}</strong>{!x.matched&&<button onClick={()=>{setBank(b=>b.map(y=>y.id===x.id?{...y,matched:true}:y));done("Bankpost matchet ✓")}}>Match</button>}</div>)}</section>{toast&&<Toast t={toast}/>}</main>;
 if(view==="status")return <main><header><Logo/><button>Testfirma ▾</button></header><section className="work"><Back/><small>STATUS</small><h1>Hvordan går det?</h1><p className="lead">Tallene forklart på vanlig norsk.</p><div className="bigstats"><Stat n="Omsetning" v={totals.sales}/><Stat n="Kostnader" v={totals.cost}/><Stat n="Resultat" v={totals.result} good/><Stat n="MVA å betale" v={totals.mva}/></div><div className="panel explain"><h2>💡 Kort forklart</h2><p>Du har solgt for <b>{money(totals.sales)}</b> denne måneden. Etter registrerte kostnader sitter firmaet foreløpig igjen med <b>{money(totals.result)}</b> før skatt.</p><p>Neste MVA-beløp i denne demoen er <b>{money(totals.mva)}</b>.</p></div></section></main>;
 return <main><header><Logo/><button>Testfirma ▾</button></header><section className="hero"><small>OVERSIKT</small><h1>Hei 👋 Hva vil du gjøre?</h1><p>Regnskap uten regnskapsspråk.</p></section><section className="grid"><Card icon="🧾" title="Jeg har kjøpt noe" text="Ta bilde eller legg inn en kvittering" go={()=>setView("receipt")}/><Card icon="💰" title="Jeg skal ha betalt" text="Lag faktura på noen få trykk" go={()=>setView("invoice")}/><Card icon="🏦" title="Bank" text="Se hva som må matches" go={()=>setView("bank")}/><Card icon="📊" title="Hvordan går det?" text="Se tallene forklart enkelt" go={()=>setView("status")}/></section><section className="status"><small>DENNE MÅNEDEN</small><h2>Hvordan går det?</h2><div className="numbers"><Stat n="Omsetning" v={totals.sales}/><Stat n="Kostnader" v={totals.cost}/><Stat n="Resultat" v={totals.result} good/><Stat n="MVA" v={totals.mva}/></div></section><nav><button onClick={()=>setView("home")}>⌂<span>Hjem</span></button><button onClick={()=>setView("receipt")}>▤<span>Bilag</span></button><button onClick={()=>setView("invoice")}>＋<span>Ny</span></button><button onClick={()=>setView("bank")}>◎<span>Bank</span></button><button onClick={()=>setView("status")}>☰<span>Mer</span></button></nav></main>
}
function Logo(){return <div><b>RALA</b><span>REGNSKAP</span></div>}
function Card({icon,title,text,go}){return <button className="card" onClick={go}><i>{icon}</i><strong>{title}</strong><em>{text}</em><b>→</b></button>}
function Stat({n,v,good}){return <p><span>{n}</span><b className={good?"plus":""}>{good?"+":""}{money(v)}</b></p>}
function Toast({t}){return <div className="toast">{t}</div>}
